// partner_portal/app/partners/[id]/page.tsx
'use client';

import { use } from 'react';
import { useRouter } from 'next/navigation';
import DashboardLayout from '@/components/dashboard/dashboard-layout';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { ArrowLeft, Building2, Phone, Mail, MapPin, CreditCard, TrendingUp } from 'lucide-react';
import { getPartnerById } from '@/lib/demo-data/partners';
import { getAgentsByPartnerId } from '@/lib/demo-data/agents';
import type { PartnerStatus } from '@/lib/types';

const statusColors: Record<PartnerStatus, string> = {
  ACTIVE: 'bg-green-100 text-green-800',
  PENDING_VERIFICATION: 'bg-yellow-100 text-yellow-800',
  SUSPENDED: 'bg-red-100 text-red-800',
  TERMINATED: 'bg-gray-100 text-gray-800',
};

export default function PartnerDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const router = useRouter();
  const partner = getPartnerById(id);
  const agents = getAgentsByPartnerId(id);

  if (!partner) {
    return (
      <DashboardLayout>
        <div className="flex flex-col items-center justify-center py-12">
          <h2 className="text-2xl font-semibold mb-2">Partner Not Found</h2>
          <p className="text-muted-foreground mb-4">The partner you're looking for doesn't exist.</p>
          <Button onClick={() => router.push('/partners')}>
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Partners
          </Button>
        </div>
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout>
      <div className="flex flex-col gap-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="sm" onClick={() => router.push('/partners')}>
              <ArrowLeft className="h-4 w-4" />
            </Button>
            <div>
              <h1 className="text-2xl font-semibold">{partner.organizationName}</h1>
              <p className="text-muted-foreground">{partner.partnerType.replace(/_/g, ' ')}</p>
            </div>
          </div>
          <Badge className={statusColors[partner.status]} variant="secondary">
            {partner.status.replace(/_/g, ' ')}
          </Badge>
        </div>

        {/* Tabs */}
        <Tabs defaultValue="overview" className="w-full">
          <TabsList>
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="documents">Documents</TabsTrigger>
            <TabsTrigger value="performance">Performance</TabsTrigger>
            <TabsTrigger value="agents">Agents ({agents.length})</TabsTrigger>
          </TabsList>

          {/* Overview Tab */}
          <TabsContent value="overview" className="space-y-6">
            <div className="grid gap-6 md:grid-cols-2">
              {/* Organization Information */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Building2 className="h-5 w-5" />
                    Organization Information
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div>
                    <div className="text-sm text-muted-foreground">Trade License</div>
                    <div className="font-medium">{partner.tradeLicense}</div>
                  </div>
                  <div>
                    <div className="text-sm text-muted-foreground">TIN Number</div>
                    <div className="font-medium">{partner.tin}</div>
                  </div>
                  <div>
                    <div className="text-sm text-muted-foreground">Partner Type</div>
                    <div className="font-medium">{partner.partnerType.replace(/_/g, ' ')}</div>
                  </div>
                </CardContent>
              </Card>

              {/* Contact Information */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Phone className="h-5 w-5" />
                    Contact Information
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex items-center gap-2">
                    <Mail className="h-4 w-4 text-muted-foreground" />
                    <div className="font-medium">{partner.contactEmail}</div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Phone className="h-4 w-4 text-muted-foreground" />
                    <div className="font-medium">{partner.contactPhone}</div>
                  </div>
                  <div className="flex items-start gap-2">
                    <MapPin className="h-4 w-4 text-muted-foreground mt-1" />
                    <div>
                      {partner.nationwideCoverage ? (
                        <span className="font-medium text-green-600">Nationwide Coverage</span>
                      ) : (
                        <div className="font-medium">{partner.serviceLocations.join(', ')}</div>
                      )}
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Bank Information */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <CreditCard className="h-5 w-5" />
                    Bank Information
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div>
                    <div className="text-sm text-muted-foreground">Bank Name</div>
                    <div className="font-medium">{partner.bankName}</div>
                  </div>
                  <div>
                    <div className="text-sm text-muted-foreground">Branch</div>
                    <div className="font-medium">{partner.bankBranch || 'N/A'}</div>
                  </div>
                  <div>
                    <div className="text-sm text-muted-foreground">Account Number</div>
                    <div className="font-medium">****{partner.bankAccount.slice(-4)}</div>
                  </div>
                </CardContent>
              </Card>

              {/* Commission Structure */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <TrendingUp className="h-5 w-5" />
                    Commission Structure
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div>
                    <div className="text-sm text-muted-foreground">Acquisition Rate</div>
                    <div className="font-medium">{partner.acquisitionRate}%</div>
                  </div>
                  <div>
                    <div className="text-sm text-muted-foreground">Renewal Rate</div>
                    <div className="font-medium">{partner.renewalRate}%</div>
                  </div>
                  {partner.claimsAssistanceRate && (
                    <div>
                      <div className="text-sm text-muted-foreground">Claims Assistance Rate</div>
                      <div className="font-medium">{partner.claimsAssistanceRate}%</div>
                    </div>
                  )}
                </CardContent>
              </Card>
            </div>

            {/* Policy Types and Service Model */}
            <Card>
              <CardHeader>
                <CardTitle>Policy Types & Service Model</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <div className="text-sm text-muted-foreground mb-2">Assigned Policy Types</div>
                  <div className="flex flex-wrap gap-2">
                    {partner.policyTypes.map((type) => (
                      <Badge key={type} variant="secondary">
                        {type}
                      </Badge>
                    ))}
                  </div>
                </div>
                <div className="grid gap-4 md:grid-cols-2">
                  <div>
                    <div className="text-sm text-muted-foreground mb-2">Cashless Service</div>
                    {partner.cashlessEnabled ? (
                      <div className="space-y-1">
                        <div className="text-green-600 font-medium">Enabled</div>
                        <div className="text-sm">
                          Limit: ৳{partner.cashlessLimit?.toLocaleString()}
                        </div>
                        {partner.autoApprovalThreshold && (
                          <div className="text-sm">
                            Auto-approval: ৳{partner.autoApprovalThreshold.toLocaleString()}
                          </div>
                        )}
                      </div>
                    ) : (
                      <div className="text-muted-foreground">Not enabled</div>
                    )}
                  </div>
                  <div>
                    <div className="text-sm text-muted-foreground mb-2">Discount Service</div>
                    {partner.discountEnabled ? (
                      <div className="space-y-1">
                        <div className="text-blue-600 font-medium">Enabled</div>
                        <div className="text-sm">
                          Discount: {partner.discountPercentage}%
                        </div>
                      </div>
                    ) : (
                      <div className="text-muted-foreground">Not enabled</div>
                    )}
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Documents Tab */}
          <TabsContent value="documents">
            <Card>
              <CardHeader>
                <CardTitle>KYB Documents</CardTitle>
                <CardDescription>
                  Know Your Business verification documents
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="text-muted-foreground">
                  Document management will be implemented in the Documents module
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Performance Tab */}
          <TabsContent value="performance">
            <div className="grid gap-6 md:grid-cols-3">
              <Card>
                <CardHeader>
                  <CardTitle>Active Policies</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-3xl font-bold">{partner.activePolicies}</div>
                  <div className="text-sm text-muted-foreground">Total policies serviced</div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Total Claims</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-3xl font-bold">{partner.totalClaims}</div>
                  <div className="text-sm text-muted-foreground">Claims submitted</div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Conversion Rate</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-3xl font-bold">{partner.conversionRate}%</div>
                  <div className="text-sm text-muted-foreground">Referral to policy</div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>

          {/* Agents Tab */}
          <TabsContent value="agents">
            <Card>
              <CardHeader>
                <CardTitle>Agents ({agents.length})</CardTitle>
                <CardDescription>
                  Insurance agents under this partner organization
                </CardDescription>
              </CardHeader>
              <CardContent>
                {agents.length === 0 ? (
                  <div className="text-center py-8 text-muted-foreground">
                    No agents registered under this partner
                  </div>
                ) : (
                  <div className="space-y-4">
                    {agents.slice(0, 10).map((agent) => (
                      <div
                        key={agent.id}
                        className="flex items-center justify-between p-4 border rounded-lg"
                      >
                        <div>
                          <div className="font-medium">{agent.fullName}</div>
                          <div className="text-sm text-muted-foreground">{agent.phone}</div>
                        </div>
                        <div className="text-right">
                          <div className="text-sm font-medium">{agent.policiesSold} policies</div>
                          <div className="text-sm text-muted-foreground">
                            ৳{agent.commissionEarned.toLocaleString()} earned
                          </div>
                        </div>
                      </div>
                    ))}
                    {agents.length > 10 && (
                      <Button
                        variant="outline"
                        className="w-full"
                        onClick={() => router.push(`/agents?partner=${id}`)}
                      >
                        View All {agents.length} Agents
                      </Button>
                    )}
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </DashboardLayout>
  );
}

// system_portal/src/routes/dashboard/partners/[id]/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { getPartnerById } from '$lib/data_detailed/partners';
	import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '$lib/components/ui/card';
	import { Badge } from '$lib/components/ui/badge';
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import * as Tabs from '$lib/components/ui/tabs';
	import * as Select from '$lib/components/ui/select';
	import { Separator } from '$lib/components/ui/separator';
	import DiscountConfigCard from '$lib/components/discount-config-card.svelte';
	import CashlessConfigCard from '$lib/components/cashless-config-card.svelte';
	import { 
		ArrowLeft, 
		Building2, 
		MapPin, 
		Phone, 
		Mail, 
		Save,
		Hospital,
		PillBottle,
		Stethoscope,
		Ambulance,
		Car,
		Laptop,
		Smartphone
	} from 'lucide-svelte';

	const partnerId = $page.params.id;
	
	// Fetch partner data from dummy data
	const partnerData = getPartnerById(partnerId);
	
	if (!partnerData) {
		goto('/dashboard/partners/life');
	}

	let partner = $state(partnerData || {
		id: partnerId,
		name: 'Unknown Partner',
		type: 'HOSPITAL',
		category: 'LIFE',
		status: 'ACTIVE',
		email: '',
		phone: '',
		address: '',
		location: '',
		discountEnabled: false,
		discountPercentage: 0,
		minDiscount: 0,
		maxDiscount: 0,
		discountType: 'SERVICE',
		cashlessEnabled: false,
		cashlessLimit: 0,
		autoApprovalThreshold: 0,
		preAuthRequired: false,
		authValidityDays: 0,
		requiredDocuments: []
	});

	const partnerTypeIcons = {
		HOSPITAL: Hospital,
		PHARMACY: PillBottle,
		DOCTOR: Stethoscope,
		AMBULANCE: Ambulance,
		AUTO_REPAIR: Car,
		LAPTOP_REPAIR: Laptop,
		MOBILE_REPAIR: Smartphone
	};

	const partnerTypeColors = {
		HOSPITAL: 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300',
		PHARMACY: 'bg-green-100 text-green-700 dark:bg-green-900 dark:text-green-300',
		DOCTOR: 'bg-purple-100 text-purple-700 dark:bg-purple-900 dark:text-purple-300',
		AMBULANCE: 'bg-red-100 text-red-700 dark:bg-red-900 dark:text-red-300',
		AUTO_REPAIR: 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900 dark:text-indigo-300',
		LAPTOP_REPAIR: 'bg-cyan-100 text-cyan-700 dark:bg-cyan-900 dark:text-cyan-300',
		MOBILE_REPAIR: 'bg-pink-100 text-pink-700 dark:bg-pink-900 dark:text-pink-300'
	};

	function handleDiscountSave(data: any) {
		console.log('Saving discount config:', data);
		// TODO: API call to save
		alert('Discount configuration saved!');
	}

	function handleCashlessSave(data: any) {
		console.log('Saving cashless config:', data);
		// TODO: API call to save
		alert('Cashless configuration saved!');
	}

	function handlePartnerUpdate() {
		console.log('Updating partner:', partner);
		// TODO: API call to update
		alert('Partner information updated!');
	}
</script>

<div class="space-y-6">
	<!-- Header -->
	<div class="flex items-center justify-between">
		<div class="flex items-center gap-4">
			<Button variant="ghost" size="icon" onclick={() => goto('/dashboard/partners/life')}>
				<ArrowLeft class="h-5 w-5" />
			</Button>
			<div>
				<div class="flex items-center gap-3">
					<div class="rounded-full p-2 {partnerTypeColors[partner.type]}">
						{@const PartnerIcon = partnerTypeIcons[partner.type]}
						<PartnerIcon class="h-6 w-6" />
					</div>
					<div>
						<h1 class="text-3xl font-bold tracking-tight">{partner.name}</h1>
						<p class="text-muted-foreground">Partner ID: {partner.id}</p>
					</div>
				</div>
			</div>
		</div>
		<div class="flex items-center gap-2">
			<Badge variant={partner.status === 'ACTIVE' ? 'default' : 'secondary'} class="text-sm">
				{partner.status}
			</Badge>
			<Badge variant="outline" class="text-sm">
				{partner.type.replace('_', ' ')}
			</Badge>
		</div>
	</div>

	<!-- Tabs -->
	<Tabs.Root value="details" class="w-full">
		<Tabs.List class="grid w-full grid-cols-3">
			<Tabs.Trigger value="details">Partner Details</Tabs.Trigger>
			<Tabs.Trigger value="discount">Discount Config</Tabs.Trigger>
			<Tabs.Trigger value="cashless">Cashless Config</Tabs.Trigger>
		</Tabs.List>

		<!-- Partner Details Tab -->
		<Tabs.Content value="details" class="space-y-4">
			<Card>
				<CardHeader>
					<CardTitle>Basic Information</CardTitle>
					<CardDescription>Manage partner's basic details and contact information</CardDescription>
				</CardHeader>
				<CardContent class="space-y-4">
					<div class="grid gap-4 md:grid-cols-2">
						<!-- Organization Name -->
						<div class="space-y-2">
							<Label for="org-name">
								Organization Name
								<span class="text-destructive">*</span>
							</Label>
							<Input id="org-name" bind:value={partner.name} placeholder="Enter organization name" />
						</div>

						<!-- Partner Type -->
						<div class="space-y-2">
							<Label for="partner-type">
								Partner Type
								<span class="text-destructive">*</span>
							</Label>
							<Select.Root bind:selected={partner.type}>
								<Select.Trigger id="partner-type">
									{partner.type || 'Select type'}
								</Select.Trigger>
								<Select.Content>
									<Select.Group>
										<Select.Label>Life Insurance Partners</Select.Label>
										<Select.Item value="HOSPITAL">Hospital</Select.Item>
										<Select.Item value="PHARMACY">Pharmacy</Select.Item>
										<Select.Item value="DOCTOR">Doctor</Select.Item>
										<Select.Item value="AMBULANCE">Ambulance</Select.Item>
									</Select.Group>
									<Select.Group>
										<Select.Label>Non-Life Partners</Select.Label>
										<Select.Item value="AUTO_REPAIR">Auto Repair</Select.Item>
										<Select.Item value="LAPTOP_REPAIR">Laptop Repair</Select.Item>
										<Select.Item value="MOBILE_REPAIR">Mobile Repair</Select.Item>
									</Select.Group>
								</Select.Content>
							</Select.Root>
						</div>

						<!-- Email -->
						<div class="space-y-2">
							<Label for="email">
								Email Address
								<span class="text-destructive">*</span>
							</Label>
							<div class="relative">
								<Mail class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
								<Input id="email" type="email" bind:value={partner.email} placeholder="email@example.com" class="pl-10" />
							</div>
						</div>

						<!-- Phone -->
						<div class="space-y-2">
							<Label for="phone">
								Phone Number
								<span class="text-destructive">*</span>
							</Label>
							<div class="relative">
								<Phone class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
								<Input id="phone" type="tel" bind:value={partner.phone} placeholder="+880 1XXX-XXXXXX" class="pl-10" />
							</div>
						</div>

						<!-- Trade License -->
						<div class="space-y-2">
							<Label for="trade-license">Trade License Number</Label>
							<Input id="trade-license" bind:value={partner.tradeLicense} placeholder="TL-XXX-XXXX-XXXXXX" />
						</div>

						<!-- TIN Number -->
						<div class="space-y-2">
							<Label for="tin">TIN Number</Label>
							<Input id="tin" bind:value={partner.tinNumber} placeholder="12-digit TIN" maxlength="12" />
						</div>
					</div>

					<!-- Address -->
					<div class="space-y-2">
						<Label for="address">
							Address
							<span class="text-destructive">*</span>
						</Label>
						<div class="relative">
							<MapPin class="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
							<Input id="address" bind:value={partner.address} placeholder="Full address" class="pl-10" />
						</div>
					</div>

					<Separator />

					<div class="flex justify-end">
						<Button onclick={handlePartnerUpdate}>
							<Save class="mr-2 h-4 w-4" />
							Save Changes
						</Button>
					</div>
				</CardContent>
			</Card>
		</Tabs.Content>

		<!-- Discount Config Tab -->
		<Tabs.Content value="discount">
			<DiscountConfigCard
				{partnerId}
				partnerName={partner.name}
				bind:discountEnabled={partner.discountEnabled}
				bind:discountPercentage={partner.discountPercentage}
				bind:minDiscount={partner.minDiscount}
				bind:maxDiscount={partner.maxDiscount}
				bind:discountType={partner.discountType}
				onSave={handleDiscountSave}
				onCancel={() => console.log('Discount config cancelled')}
			/>
		</Tabs.Content>

		<!-- Cashless Config Tab -->
		<Tabs.Content value="cashless">
			<CashlessConfigCard
				{partnerId}
				partnerName={partner.name}
				bind:cashlessEnabled={partner.cashlessEnabled}
				bind:cashlessLimit={partner.cashlessLimit}
				bind:autoApprovalThreshold={partner.autoApprovalThreshold}
				bind:preAuthRequired={partner.preAuthRequired}
				bind:authValidityDays={partner.authValidityDays}
				bind:requiredDocuments={partner.requiredDocuments}
				onSave={handleCashlessSave}
				onCancel={() => console.log('Cashless config cancelled')}
			/>
		</Tabs.Content>
	</Tabs.Root>
</div>
